# Generated by Django 5.0.7 on 2024-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_promocode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='gift',
            field=models.BooleanField(default=True),
        ),
    ]
