# Generated by Django 5.0.7 on 2024-08-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_alter_promocode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='Status',
            new_name='status',
        ),
    ]
