# Generated by Django 5.0.7 on 2024-08-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_rename_status_promocode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('gift_picture', models.ImageField(upload_to='static/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.promocode')),
            ],
        ),
    ]
