# Generated by Django 5.0.7 on 2024-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='gift',
            field=models.IntegerField(default=0),
        ),
    ]
