# Generated by Django 5.0.7 on 2024-08-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0009_creategift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creategift',
            old_name='product_name',
            new_name='gift_name',
        ),
    ]
