# Generated by Django 5.0.7 on 2024-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0010_rename_product_name_creategift_gift_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategift',
            name='gift_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='creategift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
