# Generated by Django 5.0.7 on 2024-08-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0011_creategift_gift_picture_creategift_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winning_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wcode_point', models.IntegerField(default=0)),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.promocode')),
                ('items_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.creategift')),
            ],
        ),
    ]
