# Generated by Django 5.0.7 on 2024-08-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0012_winning_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winning_code',
            old_name='Wcode_point',
            new_name='Qunatity_Produced',
        ),
    ]
