# Generated by Django 5.0.7 on 2024-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0013_rename_wcode_point_winning_code_qunatity_produced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winning_code',
            old_name='Qunatity_Produced',
            new_name='Wcode_point',
        ),
        migrations.AddField(
            model_name='creategift',
            name='QuantityProduced',
            field=models.IntegerField(default=0),
        ),
    ]
