# Generated by Django 5.0.7 on 2024-08-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0015_alter_winning_code_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winning_code',
            name='items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.creategift'),
        ),
    ]
