# Generated by Django 5.0.7 on 2024-08-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0020_alter_winning_code_voucher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winning_code',
            name='Voucher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.promocode'),
        ),
    ]
