# Generated by Django 5.0.7 on 2024-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0021_alter_winning_code_voucher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='gift',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
