# Generated by Django 5.0.7 on 2024-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0022_alter_promocode_gift_alter_promocode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
